node {
    def myNodeContainer = docker.image('node:latest')
    myNodeContainer.pull()

    stage('prep') {
        git url: 'https://github.com/maityneil001/express-demo.git'
    }

    stage('build') {
      myNodeContainer.inside {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
    }

    stage('sonar-scanner') {
      def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
      withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
        sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=express-demo -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=ExpD -Dsonar.sources=. -Dsonar.tests=./test/ -Dsonar.language=JavaScript -Dsonar.java.binaries=."
      }
    }
}
